/// Flutter icons WeatherIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcon
///      fonts:
///       - asset: fonts/WeatherIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class WeatherIcon {
  WeatherIcon._();

  static const _kFontFam = 'WeatherIcon';

  static const IconData glyph_52 = const IconData(0xf000, fontFamily: _kFontFam);
  static const IconData glyph_53 = const IconData(0xf001, fontFamily: _kFontFam);
  static const IconData glyph_54 = const IconData(0xf002, fontFamily: _kFontFam);
  static const IconData glyph_55 = const IconData(0xf003, fontFamily: _kFontFam);
  static const IconData glyph_56 = const IconData(0xf004, fontFamily: _kFontFam);
  static const IconData glyph_57 = const IconData(0xf005, fontFamily: _kFontFam);
  static const IconData glyph_58 = const IconData(0xf006, fontFamily: _kFontFam);
  static const IconData glyph_60 = const IconData(0xf007, fontFamily: _kFontFam);
  static const IconData glyph_59 = const IconData(0xf008, fontFamily: _kFontFam);
  static const IconData glyph_61 = const IconData(0xf009, fontFamily: _kFontFam);
  static const IconData glyph_62 = const IconData(0xf00a, fontFamily: _kFontFam);
  static const IconData glyph_63 = const IconData(0xf00b, fontFamily: _kFontFam);
  static const IconData glyph_65 = const IconData(0xf00c, fontFamily: _kFontFam);
  static const IconData glyph_64 = const IconData(0xf00d, fontFamily: _kFontFam);
  static const IconData glyph_66 = const IconData(0xf00e, fontFamily: _kFontFam);
  static const IconData glyph_67 = const IconData(0xf010, fontFamily: _kFontFam);
  static const IconData glyph_68 = const IconData(0xf011, fontFamily: _kFontFam);
  static const IconData glyph_69 = const IconData(0xf012, fontFamily: _kFontFam);
  static const IconData glyph_70 = const IconData(0xf013, fontFamily: _kFontFam);
  static const IconData glyph_90 = const IconData(0xf014, fontFamily: _kFontFam);
  static const IconData glyph_89 = const IconData(0xf015, fontFamily: _kFontFam);
  static const IconData glyph_88 = const IconData(0xf016, fontFamily: _kFontFam);
  static const IconData glyph_87 = const IconData(0xf017, fontFamily: _kFontFam);
  static const IconData glyph_85 = const IconData(0xf018, fontFamily: _kFontFam);
  static const IconData glyph_86 = const IconData(0xf019, fontFamily: _kFontFam);
  static const IconData glyph_84 = const IconData(0xf01a, fontFamily: _kFontFam);
  static const IconData glyph_83 = const IconData(0xf01b, fontFamily: _kFontFam);
  static const IconData glyph_82 = const IconData(0xf01c, fontFamily: _kFontFam);
  static const IconData glyph_81 = const IconData(0xf01d, fontFamily: _kFontFam);
  static const IconData glyph_80 = const IconData(0xf01e, fontFamily: _kFontFam);
  static const IconData glyph_79 = const IconData(0xf021, fontFamily: _kFontFam);
  static const IconData glyph_78 = const IconData(0xf022, fontFamily: _kFontFam);
  static const IconData glyph_77 = const IconData(0xf023, fontFamily: _kFontFam);
  static const IconData glyph_76 = const IconData(0xf024, fontFamily: _kFontFam);
  static const IconData glyph_75 = const IconData(0xf025, fontFamily: _kFontFam);
  static const IconData glyph_74 = const IconData(0xf026, fontFamily: _kFontFam);
  static const IconData glyph_73 = const IconData(0xf027, fontFamily: _kFontFam);
  static const IconData glyph_72 = const IconData(0xf028, fontFamily: _kFontFam);
  static const IconData glyph_71 = const IconData(0xf029, fontFamily: _kFontFam);
  static const IconData glyph_91 = const IconData(0xf02a, fontFamily: _kFontFam);
  static const IconData glyph_92 = const IconData(0xf02b, fontFamily: _kFontFam);
  static const IconData glyph_93 = const IconData(0xf02c, fontFamily: _kFontFam);
  static const IconData glyph_94 = const IconData(0xf02d, fontFamily: _kFontFam);
  static const IconData glyph_95 = const IconData(0xf02e, fontFamily: _kFontFam);
  static const IconData glyph_96 = const IconData(0xf02f, fontFamily: _kFontFam);
  static const IconData glyph_97 = const IconData(0xf030, fontFamily: _kFontFam);
  static const IconData glyph_98 = const IconData(0xf031, fontFamily: _kFontFam);
  static const IconData glyph_99 = const IconData(0xf032, fontFamily: _kFontFam);
  static const IconData glyph_100 = const IconData(0xf033, fontFamily: _kFontFam);
  static const IconData glyph_101 = const IconData(0xf034, fontFamily: _kFontFam);
  static const IconData glyph_102 = const IconData(0xf035, fontFamily: _kFontFam);
  static const IconData glyph_103 = const IconData(0xf036, fontFamily: _kFontFam);
  static const IconData glyph_105 = const IconData(0xf037, fontFamily: _kFontFam);
  static const IconData glyph_104 = const IconData(0xf038, fontFamily: _kFontFam);
  static const IconData glyph_106 = const IconData(0xf039, fontFamily: _kFontFam);
  static const IconData glyph_107 = const IconData(0xf03a, fontFamily: _kFontFam);
  static const IconData glyph_108 = const IconData(0xf03b, fontFamily: _kFontFam);
  static const IconData glyph_109 = const IconData(0xf03c, fontFamily: _kFontFam);
  static const IconData glyph_110 = const IconData(0xf03d, fontFamily: _kFontFam);
  static const IconData glyph_130 = const IconData(0xf03e, fontFamily: _kFontFam);
  static const IconData glyph_129 = const IconData(0xf040, fontFamily: _kFontFam);
  static const IconData glyph_128 = const IconData(0xf041, fontFamily: _kFontFam);
  static const IconData glyph_127 = const IconData(0xf042, fontFamily: _kFontFam);
  static const IconData glyph_126 = const IconData(0xf043, fontFamily: _kFontFam);
  static const IconData glyph_125 = const IconData(0xf044, fontFamily: _kFontFam);
  static const IconData glyph_124 = const IconData(0xf045, fontFamily: _kFontFam);
  static const IconData glyph_123 = const IconData(0xf046, fontFamily: _kFontFam);
  static const IconData glyph_122 = const IconData(0xf047, fontFamily: _kFontFam);
  static const IconData glyph_121 = const IconData(0xf048, fontFamily: _kFontFam);
  static const IconData glyph_120 = const IconData(0xf04a, fontFamily: _kFontFam);
  static const IconData glyph_119 = const IconData(0xf04b, fontFamily: _kFontFam);
  static const IconData glyph_118 = const IconData(0xf04c, fontFamily: _kFontFam);
  static const IconData glyph_117 = const IconData(0xf04d, fontFamily: _kFontFam);
  static const IconData glyph_116 = const IconData(0xf04e, fontFamily: _kFontFam);
  static const IconData glyph_115 = const IconData(0xf050, fontFamily: _kFontFam);
  static const IconData glyph_114 = const IconData(0xf051, fontFamily: _kFontFam);
  static const IconData glyph_113 = const IconData(0xf052, fontFamily: _kFontFam);
  static const IconData glyph_112 = const IconData(0xf053, fontFamily: _kFontFam);
  static const IconData glyph_111 = const IconData(0xf054, fontFamily: _kFontFam);
  static const IconData glyph_131 = const IconData(0xf055, fontFamily: _kFontFam);
  static const IconData glyph_132 = const IconData(0xf056, fontFamily: _kFontFam);
  static const IconData glyph_133 = const IconData(0xf057, fontFamily: _kFontFam);
  static const IconData glyph_134 = const IconData(0xf058, fontFamily: _kFontFam);
  static const IconData glyph_135 = const IconData(0xf059, fontFamily: _kFontFam);
  static const IconData glyph_136 = const IconData(0xf05a, fontFamily: _kFontFam);
  static const IconData glyph_137 = const IconData(0xf05b, fontFamily: _kFontFam);
  static const IconData glyph_138 = const IconData(0xf05c, fontFamily: _kFontFam);
  static const IconData glyph_139 = const IconData(0xf05d, fontFamily: _kFontFam);
  static const IconData glyph_140 = const IconData(0xf05e, fontFamily: _kFontFam);
  static const IconData glyph_141 = const IconData(0xf060, fontFamily: _kFontFam);
  static const IconData glyph_142 = const IconData(0xf061, fontFamily: _kFontFam);
  static const IconData glyph_143 = const IconData(0xf062, fontFamily: _kFontFam);
  static const IconData glyph_144 = const IconData(0xf063, fontFamily: _kFontFam);
  static const IconData glyph_145 = const IconData(0xf064, fontFamily: _kFontFam);
  static const IconData glyph_146 = const IconData(0xf065, fontFamily: _kFontFam);
  static const IconData glyph_148 = const IconData(0xf066, fontFamily: _kFontFam);
  static const IconData glyph_147 = const IconData(0xf067, fontFamily: _kFontFam);
  static const IconData glyph_149 = const IconData(0xf068, fontFamily: _kFontFam);
  static const IconData glyph_150 = const IconData(0xf069, fontFamily: _kFontFam);
  static const IconData glyph_162 = const IconData(0xf06a, fontFamily: _kFontFam);
  static const IconData glyph_161 = const IconData(0xf06b, fontFamily: _kFontFam);
  static const IconData glyph_160 = const IconData(0xf06c, fontFamily: _kFontFam);
  static const IconData glyph_159 = const IconData(0xf06d, fontFamily: _kFontFam);
  static const IconData glyph_158 = const IconData(0xf06e, fontFamily: _kFontFam);
  static const IconData glyph_157 = const IconData(0xf070, fontFamily: _kFontFam);
  static const IconData glyph_156 = const IconData(0xf071, fontFamily: _kFontFam);
  static const IconData glyph_155 = const IconData(0xf072, fontFamily: _kFontFam);
  static const IconData glyph_154 = const IconData(0xf073, fontFamily: _kFontFam);
  static const IconData glyph_169 = const IconData(0xf074, fontFamily: _kFontFam);
  static const IconData glyph_152 = const IconData(0xf075, fontFamily: _kFontFam);
  static const IconData glyph_151 = const IconData(0xf076, fontFamily: _kFontFam);
  static const IconData glyph_153 = const IconData(0xf077, fontFamily: _kFontFam);
  static const IconData glyph_163 = const IconData(0xf083, fontFamily: _kFontFam);
  static const IconData glyph_164 = const IconData(0xf084, fontFamily: _kFontFam);
  static const IconData glyph_165 = const IconData(0xf085, fontFamily: _kFontFam);
  static const IconData glyph_166 = const IconData(0xf086, fontFamily: _kFontFam);
  static const IconData glyph_167 = const IconData(0xf087, fontFamily: _kFontFam);
  static const IconData glyph_168 = const IconData(0xf088, fontFamily: _kFontFam);
  static const IconData glyph_170 = const IconData(0xf089, fontFamily: _kFontFam);
  static const IconData glyph_171 = const IconData(0xf08a, fontFamily: _kFontFam);
  static const IconData glyph_172 = const IconData(0xf08b, fontFamily: _kFontFam);
  static const IconData glyph_173 = const IconData(0xf08c, fontFamily: _kFontFam);
  static const IconData glyph_174 = const IconData(0xf08d, fontFamily: _kFontFam);
  static const IconData glyph_175 = const IconData(0xf08e, fontFamily: _kFontFam);
  static const IconData glyph_176 = const IconData(0xf08f, fontFamily: _kFontFam);
  static const IconData glyph_28 = const IconData(0xf090, fontFamily: _kFontFam);
  static const IconData glyph_29 = const IconData(0xf091, fontFamily: _kFontFam);
  static const IconData glyph_30 = const IconData(0xf092, fontFamily: _kFontFam);
  static const IconData glyph_31 = const IconData(0xf093, fontFamily: _kFontFam);
  static const IconData glyph_51 = const IconData(0xf094, fontFamily: _kFontFam);
  static const IconData glyph_50 = const IconData(0xf095, fontFamily: _kFontFam);
  static const IconData glyph_49 = const IconData(0xf096, fontFamily: _kFontFam);
  static const IconData glyph_48 = const IconData(0xf097, fontFamily: _kFontFam);
  static const IconData glyph_47 = const IconData(0xf098, fontFamily: _kFontFam);
  static const IconData glyph_46 = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData glyph_45 = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData glyph_44 = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData glyph_43 = const IconData(0xf09c, fontFamily: _kFontFam);
  static const IconData glyph_42 = const IconData(0xf09d, fontFamily: _kFontFam);
  static const IconData glyph_41 = const IconData(0xf09e, fontFamily: _kFontFam);
  static const IconData glyph_40 = const IconData(0xf09f, fontFamily: _kFontFam);
  static const IconData glyph_39 = const IconData(0xf0a0, fontFamily: _kFontFam);
  static const IconData glyph_38 = const IconData(0xf0a1, fontFamily: _kFontFam);
  static const IconData glyph_37 = const IconData(0xf0a2, fontFamily: _kFontFam);
  static const IconData glyph_36 = const IconData(0xf0a3, fontFamily: _kFontFam);
  static const IconData glyph_35 = const IconData(0xf0a4, fontFamily: _kFontFam);
  static const IconData glyph_34 = const IconData(0xf0a5, fontFamily: _kFontFam);
  static const IconData glyph_33 = const IconData(0xf0a6, fontFamily: _kFontFam);
  static const IconData glyph_32 = const IconData(0xf0a7, fontFamily: _kFontFam);
  static const IconData glyph_12 = const IconData(0xf0a8, fontFamily: _kFontFam);
  static const IconData glyph_9 = const IconData(0xf0a9, fontFamily: _kFontFam);
  static const IconData glyph_10 = const IconData(0xf0aa, fontFamily: _kFontFam);
  static const IconData glyph_11 = const IconData(0xf0ab, fontFamily: _kFontFam);
  static const IconData glyph_5 = const IconData(0xf0ac, fontFamily: _kFontFam);
  static const IconData glyph_13 = const IconData(0xf0ad, fontFamily: _kFontFam);
  static const IconData glyph_14 = const IconData(0xf0ae, fontFamily: _kFontFam);
  static const IconData glyph_15 = const IconData(0xf0af, fontFamily: _kFontFam);
  static const IconData glyph_16 = const IconData(0xf0b0, fontFamily: _kFontFam);
  static const IconData glyph_17 = const IconData(0xf0b1, fontFamily: _kFontFam);
  static const IconData glyph_18 = const IconData(0xf0b2, fontFamily: _kFontFam);
  static const IconData glyph_19 = const IconData(0xf0b3, fontFamily: _kFontFam);
  static const IconData glyph_20 = const IconData(0xf0b4, fontFamily: _kFontFam);
  static const IconData glyph_21 = const IconData(0xf0b5, fontFamily: _kFontFam);
  static const IconData glyph_22 = const IconData(0xf0b6, fontFamily: _kFontFam);
  static const IconData glyph_23 = const IconData(0xf0b7, fontFamily: _kFontFam);
  static const IconData glyph_24 = const IconData(0xf0b8, fontFamily: _kFontFam);
  static const IconData glyph_25 = const IconData(0xf0b9, fontFamily: _kFontFam);
  static const IconData glyph_26 = const IconData(0xf0ba, fontFamily: _kFontFam);
  static const IconData glyph_27 = const IconData(0xf0bb, fontFamily: _kFontFam);
  static const IconData glyph_8 = const IconData(0xf0bc, fontFamily: _kFontFam);
  static const IconData glyph_7 = const IconData(0xf0bd, fontFamily: _kFontFam);
  static const IconData glyph_6 = const IconData(0xf0be, fontFamily: _kFontFam);
  static const IconData glyph_3 = const IconData(0xf0bf, fontFamily: _kFontFam);
  static const IconData glyph_4 = const IconData(0xf0c0, fontFamily: _kFontFam);
  static const IconData glyph_2 = const IconData(0xf0c1, fontFamily: _kFontFam);
  static const IconData glyph_1 = const IconData(0xf0c2, fontFamily: _kFontFam);
  static const IconData glyph = const IconData(0xf0c3, fontFamily: _kFontFam);
  static const IconData rebel = const IconData(0xf1d0, fontFamily: _kFontFam);
}
